# -*- coding: utf-8 -*-
"""
CH5 Part 1: Modules 1 to 10
Life Processes (Class 10 Science)
"""
import json

with open('scratch/ch5_bank_questions.json', 'r', encoding='utf-8') as f:
    bank_questions = json.load(f)

bank_by_id = {q['id']: q for q in bank_questions}

def get_bank_q(qid, new_id):
    q = bank_by_id[qid]
    opts = [opt['text'] for opt in q['options']]
    correct_key = q['correct_option']
    correct_text = next(opt['text'] for opt in q['options'] if opt['key'] == correct_key)
    qtext = q['question'].replace('NCERT', 'standard curriculum')
    exp = q['explanation'].replace('NCERT', 'standard curriculum')
    return {
        "id": new_id,
        "question": qtext,
        "options": opts,
        "answer": correct_text,
        "explanation": exp
    }

modules_1_to_10 = []

# Module 1
m01 = {
  "id": "m01", "moduleNumber": 1,
  "title": "What are Life Processes? Molecular Movements & Biological Maintenance",
  "tagline": "Criteria for life, cellular repair mechanisms, and maintaining molecular order.",
  "readingTimeMins": 5,
  "theoryHtml": r"""
<p>What criteria decide whether an organism is alive? While visible movements—such as walking, running, breathing, or a dog barking—are obvious signs of life in animals, they fail to explain life in plants or dormant seeds, which do not show rapid visible motion. Even asleep, living organisms carry on unseen activities.</p>

<h3>Invisible Molecular Movements — The Defining Hallmark of Life:</h3>
<ul>
  <li>Living organisms are complex, highly organized cellular structures composed of tissues, cells, organelles, and molecules.</li>
  <li>Because of environmental entropy and continuous thermodynamic breakdown, these organized structures tend to deteriorate over time. If this molecular order completely breaks down, the organism dies.</li>
  <li>Therefore, living creatures must continuously repair, rebuild, and maintain their structures through <strong>incessant, invisible molecular movements</strong> occurring across cell membranes and within cytoplasm.</li>
</ul>

<h3>The Four Foundational Life Processes:</h3>
<p>The basic processes that together perform this essential maintenance job and keep an organism alive are defined as <strong>life processes</strong>:</p>
<ol>
  <li><strong>Nutrition:</strong> The process of acquiring energy sources (food) from outside the body into the organism to sustain life, growth, and repair.</li>
  <li><strong>Respiration:</strong> The biochemical process of acquiring oxygen from outside to break down carbon-based food sources inside cells for cellular energy release (ATP).</li>
  <li><strong>Transportation:</strong> The internal distribution mechanism that moves absorbed food nutrients, water, gases, and hormones to all cells throughout the organism's body.</li>
  <li><strong>Excretion:</strong> The biological removal of toxic, harmful metabolic byproducts (especially nitrogenous wastes like urea and uric acid) generated by cellular metabolism.</li>
</ol>
""",
  "pointsToRemember": [
    "Invisible molecular movements are the true defining characteristic of living organisms.",
    "Life processes are the essential maintenance functions needed to sustain life: Nutrition, Respiration, Transportation, and Excretion.",
    "Continuous energy input and molecular repair are required to prevent structural decay and biological death."
  ],
  "keyNotes": [
    "Conceptual Question: Why are molecular movements needed for life? Because living structures are organized; without continuous repair by molecular movement, thermodynamic decay causes death."
  ],
  "questions": [
    get_bank_q(1, "m01_q01"), get_bank_q(2, "m01_q02"), get_bank_q(3, "m01_q03"),
    get_bank_q(4, "m01_q04"), get_bank_q(5, "m01_q05"),
    {
      "id": "m01_q06",
      "question": "Why is visible macroscopic movement alone NOT considered a sufficient criterion to define living organisms?",
      "options": [
        "Animals do not move when awake.",
        "Plants and dormant seeds show no obvious visible movement, yet carry on essential internal molecular life processes.",
        "Rocks move faster than animals.",
        "Visible movement requires zero energy."
      ],
      "answer": "Plants and dormant seeds show no obvious visible movement, yet carry on essential internal molecular life processes.",
      "explanation": "Plants do not show rapid locomotion, and sleeping animals show minimal movement, yet both maintain vital cellular molecular life processes."
    },
    {
      "id": "m01_q07",
      "question": "Why do viruses exist on the borderline of living and non-living until they enter a host cell?",
      "options": [
        "They are made of rock crystals.",
        "They show no molecular movement whatsoever outside a host cell; molecular replication occurs only by hijacking a host cell's machinery.",
        "They carry out photosynthesis in sunlight.",
        "They are too large to be classified as cells."
      ],
      "answer": "They show no molecular movement whatsoever outside a host cell; molecular replication occurs only by hijacking a host cell's machinery.",
      "explanation": "Viruses lack metabolic molecular machinery outside hosts, exhibiting life characteristics only inside living cells."
    },
    {
      "id": "m01_q08",
      "question": "What is the primary biological purpose of 'maintenance processes' in a multicellular organism at rest or asleep?",
      "options": [
        "To cool the body to absolute zero.",
        "To prevent breakdown and decay of organized cellular structures and ensure survival.",
        "To convert all water into gas.",
        "To stop heartbeats temporarily."
      ],
      "answer": "To prevent breakdown and decay of organized cellular structures and ensure survival.",
      "explanation": "Even at rest, energy is required to maintain cellular integrity and sustain basal metabolic homeostasis."
    },
    {
      "id": "m01_q09",
      "question": "Which of the following processes is responsible for eliminating toxic nitrogenous waste products generated by cellular biochemical reactions?",
      "options": [
        "Ingestion",
        "Excretion",
        "Transpiration",
        "Fermentation"
      ],
      "answer": "Excretion",
      "explanation": "Excretion specifically refers to the biological removal of metabolic waste products, particularly toxic nitrogenous compounds."
    },
    {
      "id": "m01_q10",
      "question": "Why do simple unicellular organisms (like Amoeba) not require specialized circulatory or respiratory organ systems?",
      "options": [
        "They do not require oxygen.",
        "Their entire cell surface is in direct contact with the external environment, allowing diffusion to satisfy all nutrient and gas exchange needs.",
        "They use artificial pumps.",
        "Their cytoplasm is solid bone."
      ],
      "answer": "Their entire cell surface is in direct contact with the external environment, allowing diffusion to satisfy all nutrient and gas exchange needs.",
      "explanation": "In single-celled organisms, diffusion across the plasma membrane is sufficient because diffusion distances are microscopic."
    }
  ]
}
modules_1_to_10.append(m01)

# Module 2
m02 = {
  "id": "m02", "moduleNumber": 2,
  "title": "Autotrophic Nutrition & The Photosynthesis Equation",
  "tagline": "Converting inorganic carbon dioxide and water into energy-rich carbohydrates.",
  "readingTimeMins": 5,
  "theoryHtml": r"""
<p><strong>Autotrophic nutrition</strong> is the mode of nutrition in which organisms manufacture their own organic food from simple inorganic materials ($\text{CO}_2$ and $\text{H}_2\text{O}$) in the presence of sunlight and chlorophyll. Organisms exhibiting this mode are called <strong>autotrophs</strong> (green plants and certain autotrophic bacteria).</p>

<h3>The Biochemical Process of Photosynthesis:</h3>
<p>Photosynthesis is the fundamental physiological process by which green plants trap solar radiant energy and convert it into chemical potential energy stored in the bonds of glucose and starch.</p>

<h3>The Overall Balanced Chemical Equation of Photosynthesis:</h3>
<p style="text-align:center; font-weight:bold; font-size:1.15em; color:#166534; background:#f0fdf4; padding:12px; border-radius:8px; border:1px solid #bbf7d0;">
  $6\text{CO}_2 + 12\text{H}_2\text{O} \xrightarrow[\text{Sunlight}]{\text{Chlorophyll}} \text{C}_6\text{H}_{12}\text{O}_6 + 6\text{O}_2 + 6\text{H}_2\text{O}$
</p>

<h3>Storage of Energy:</h3>
<ul>
  <li>The carbohydrates synthesized are used immediately to provide energy for cellular activities.</li>
  <li>Carbohydrates that are not used immediately are stored as <strong>starch</strong> in plants, serving as an internal energy reserve.</li>
  <li>In humans and animals, excess carbohydrates are similarly stored in the liver and muscles as <strong>glycogen</strong>.</li>
</ul>
""",
  "pointsToRemember": [
    "Autotrophs convert CO₂ and H₂O into glucose (C₆H₁₂O₆) using sunlight trapped by chlorophyll.",
    "Overall balanced equation: 6CO₂ + 12H₂O → C₆H₁₂O₆ + 6O₂ + 6H₂O (in sunlight & chlorophyll).",
    "Excess carbohydrates are stored as starch in plants and as glycogen in animals."
  ],
  "keyNotes": [
    "Board Highlight: Memorize the exact balanced equation for photosynthesis showing 12 molecules of H₂O on the reactant side and 6 molecules of H₂O on the product side!"
  ],
  "questions": [
    get_bank_q(6, "m02_q01"), get_bank_q(7, "m02_q02"), get_bank_q(8, "m02_q03"),
    get_bank_q(9, "m02_q04"), get_bank_q(10, "m02_q05"),
    {
      "id": "m02_q06",
      "question": "What is the primary chemical form in which unused carbohydrates synthesized during photosynthesis are stored in plant tissues?",
      "options": [
        "Glycogen",
        "Starch",
        "Cellulose fibers",
        "Liquid amino acids"
      ],
      "answer": "Starch",
      "explanation": "Plants store surplus photosynthetic carbohydrates as insoluble starch granules, which serve as internal energy reserves."
    },
    {
      "id": "m02_q07",
      "question": "In what biological storage form do human beings and animals store unutilised carbohydrates derived from food?",
      "options": [
        "Starch",
        "Glycogen (stored in liver and muscles)",
        "Sucrose",
        "Chlorophyll"
      ],
      "answer": "Glycogen (stored in liver and muscles)",
      "explanation": "Animals store excess glucose as branched glycogen in hepatic (liver) and skeletal muscle tissues."
    },
    {
      "id": "m02_q08",
      "question": "What green photosynthetic organelle inside plant leaf mesophyll cells contains chlorophyll pigments?",
      "options": [
        "Mitochondria",
        "Chloroplasts",
        "Golgi apparatus",
        "Ribosomes"
      ],
      "answer": "Chloroplasts",
      "explanation": "Chloroplasts are the specialised plant organelles containing chlorophyll that capture light energy for photosynthesis."
    },
    {
      "id": "m02_q09",
      "question": "During the photosynthesis equation 6CO₂ + 12H₂O → C₆H₁₂O₆ + 6O₂ + 6H₂O, what is the chemical origin of the oxygen gas (O₂) released?",
      "options": [
        "Atmospheric carbon dioxide (CO₂)",
        "Water molecules (H₂O) split during light reactions",
        "Glucose breakdown",
        "Soil nitrate ions"
      ],
      "answer": "Water molecules (H₂O) split during light reactions",
      "explanation": "Photolysis of water molecules (2H₂O -> 4H⁺ + 4e- + O₂) releases oxygen gas into the atmosphere."
    },
    {
      "id": "m02_q10",
      "question": "Which of the following organisms exhibits autotrophic nutrition?",
      "options": [
        "Yeast (fungus)",
        "Mushroom",
        "Green plants and cyanobacteria",
        "Amoeba"
      ],
      "answer": "Green plants and cyanobacteria",
      "explanation": "Green plants and photosynthetic bacteria synthesise their own food from inorganic CO₂ and water using sunlight."
    }
  ]
}
modules_1_to_10.append(m02)

# Module 3
m03 = {
  "id": "m03", "moduleNumber": 3,
  "title": "The Three Key Events of Photosynthesis: Light & Dark Reactions",
  "tagline": "Photon absorption, photolysis of water, and carbon dioxide reduction.",
  "readingTimeMins": 5,
  "theoryHtml": r"""
<p>Photosynthesis is not a single-step reaction, but an orchestrated sequence of biochemical reactions occurring inside the chloroplasts. Three major events take place during this process:</p>

<h3>The Three Major Events of Photosynthesis:</h3>
<ol>
  <li><strong>Absorption of Light Energy:</strong><br>
  Chlorophyll molecules embedded in the thylakoid membranes of chloroplasts absorb photons from solar radiation (predominantly in the blue and red wavelengths of the visible spectrum).</li>
  <li><strong>Conversion & Photolysis of Water:</strong><br>
  The absorbed light energy is converted into <strong>chemical energy</strong> ($\text{ATP}$ and $\text{NADPH}$). Simultaneously, water molecules are split into hydrogen and oxygen through <strong>photolysis</strong>:
  $$2\text{H}_2\text{O} \xrightarrow{\text{Light energy}} 4\text{H}^+ + 4e^- + \text{O}_2 \uparrow$$
  <em>Crucial Fact:</em> The oxygen gas released during photosynthesis comes entirely from <strong>water ($\text{H}_2\text{O}$)</strong>, NOT from carbon dioxide!</li>
  <li><strong>Reduction of Carbon Dioxide:</strong><br>
  Hydrogen ions and chemical energy ($\text{NADPH}$ and $\text{ATP}$) generated in the light phase are used to <strong>reduce carbon dioxide ($\text{CO}_2$) to carbohydrates</strong> (glucose, $\text{C}_6\text{H}_{12}\text{O}_6$).</li>
</ol>

<h3>Temporal Separation in Desert Plants (CAM Adaptation):</h3>
<p>These three steps do not necessarily have to take place one immediately after the other! For example, <strong>desert plants (xerophytes)</strong> keep their stomata tightly closed during the scorching daytime to prevent fatal water loss (transpiration). Instead, they open stomata at night to absorb $\text{CO}_2$ and store it as an intermediate organic acid (malic acid). During the daytime, when sunlight is abundant, this stored intermediate is broken down to complete the reduction of $\text{CO}_2$!</p>
""",
  "pointsToRemember": [
    "1. Chlorophyll absorbs light energy.",
    "2. Light energy splits water molecules into hydrogen and oxygen (photolysis); oxygen comes from H₂O.",
    "3. Carbon dioxide is reduced to carbohydrates using the chemical energy produced.",
    "Desert plants absorb CO₂ at night as an intermediate to prevent daytime water loss."
  ],
  "keyNotes": [
    "Exam Question: State the three events of photosynthesis and explain how desert plants adapt the timing of CO₂ absorption to conserve water."
  ],
  "questions": [
    get_bank_q(61, "m03_q01"), get_bank_q(62, "m03_q02"), get_bank_q(63, "m03_q03"),
    get_bank_q(64, "m03_q04"), get_bank_q(65, "m03_q05"),
    {
      "id": "m03_q06",
      "question": "What is the biological significance of the photolysis of water during the light reaction of photosynthesis?",
      "options": [
        "It generates carbon dioxide for the plant.",
        "It splits H₂O into protons, electrons, and liberates oxygen gas (O₂).",
        "It cools the roots of the plant.",
        "It breaks down starch into sucrose."
      ],
      "answer": "It splits H₂O into protons, electrons, and liberates oxygen gas (O₂).",
      "explanation": "Photolysis splits water to provide electrons and protons for NADP+ reduction while evolving O₂ as a byproduct."
    },
    {
      "id": "m03_q07",
      "question": "How do desert plants (xerophytes) modify the standard timing of photosynthesis to prevent excessive water loss?",
      "options": [
        "They carry out photosynthesis exclusively underground.",
        "They open stomata at night to take up CO₂ and store it as an intermediate acid, completing reduction during the day using sunlight.",
        "They stop photosynthesising completely.",
        "They absorb oxygen instead of carbon dioxide."
      ],
      "answer": "They open stomata at night to take up CO₂ and store it as an intermediate acid, completing reduction during the day using sunlight.",
      "explanation": "Desert plants use Crassulacean Acid Metabolism (CAM): stomata open at night to fix CO₂, minimizing transpiration."
    },
    {
      "id": "m03_q08",
      "question": "During the reduction phase of photosynthesis, carbon dioxide (CO₂) is chemically reduced to form:",
      "options": [
        "Lipids",
        "Carbohydrates (such as Glucose, C₆H₁₂O₆)",
        "Proteins",
        "Mineral salts"
      ],
      "answer": "Carbohydrates (such as Glucose, C₆H₁₂O₆)",
      "explanation": "CO₂ is reduced by assimilatory power (ATP and NADPH) into triose phosphates, which combine to form glucose."
    },
    {
      "id": "m03_q09",
      "question": "Which of the following events occurs FIRST when a beam of sunlight strikes a green leaf?",
      "options": [
        "Synthesis of starch",
        "Absorption of photon energy by chlorophyll pigments",
        "Evolution of oxygen gas",
        "Opening of root xylem vessels"
      ],
      "answer": "Absorption of photon energy by chlorophyll pigments",
      "explanation": "Photosynthesis is triggered by the initial capture of solar photons by antenna pigments in chlorophyll."
    },
    {
      "id": "m03_q10",
      "question": "In a laboratory experiment with heavy oxygen isotope (¹⁸O), water containing H₂¹⁸O was fed to a plant. Where was the ¹⁸O isotope detected?",
      "options": [
        "Inside the glucose molecules (C₆H₁₂O₆)",
        "In the liberated oxygen gas (¹⁸O₂)",
        "In the cell wall cellulose only",
        "Inside the root minerals"
      ],
      "answer": "In the liberated oxygen gas (¹⁸O₂)",
      "explanation": "Ruben and Kamen proved via isotopic labeling that evolved oxygen originates from water (H₂O), not from CO₂."
    }
  ]
}
modules_1_to_10.append(m03)

# Module 4
m04 = {
  "id": "m04", "moduleNumber": 4,
  "title": "Stomata & Guard Cells: Osmotic Mechanism & Transpiration Loss",
  "tagline": "Turgor-driven stomatal pore regulation and balancing gas exchange with water conservation.",
  "readingTimeMins": 5,
  "theoryHtml": r"""
<p>Plants need massive volumes of carbon dioxide for photosynthesis. How does this gas enter the leaf tissues? Gas exchange occurs through microscopic apertures called <strong>stomata</strong> (singular: stoma), situated predominantly on the lower epidermis of leaves.</p>

<h3>Anatomy of a Stoma:</h3>
<ul>
  <li>Each stomatal pore is flanked by a pair of specialised, kidney-shaped (or bean-shaped) cells called <strong>guard cells</strong>.</li>
  <li>Guard cells contain chloroplasts and have an <strong>elastic, thin outer wall</strong> and a <strong>thick, inelastic inner wall</strong> facing the pore.</li>
</ul>

<h3>The Osmotic Mechanism of Stomatal Opening & Closing:</h3>
<p>The opening and closing of the stomatal pore is a function of the <strong>turgidity of the guard cells</strong>:</p>
<ol>
  <li><strong>Opening of Stomata (Daytime):</strong><br>
  When water flows into the guard cells from neighbouring epidermal cells by <strong>endosmosis</strong>, the guard cells swell and become <strong>turgid</strong>. The thin outer wall expands outwards, pulling the thick inner elastic wall with it, causing the stomatal pore to <strong>open wide</strong>.</li>
  <li><strong>Closing of Stomata (Night or Water Stress):</strong><br>
  When the guard cells lose water by <strong>exosmosis</strong>, they become <strong>flaccid</strong> (shrink). The elastic inner walls snap back together, causing the stomatal pore to <strong>close completely</strong>.</li>
</ol>

<h3>The Plant Dilemma: Gas Exchange vs Transpiration Loss:</h3>
<p>Since massive amounts of water vapour are lost through open stomata by <strong>transpiration</strong>, the plant closes these pores whenever it does not require carbon dioxide for photosynthesis, preserving vital moisture.</p>
""",
  "pointsToRemember": [
    "Stomatal pores are regulated by a pair of kidney-shaped guard cells.",
    "When guard cells absorb water and become turgid, the pore opens; when they lose water and become flaccid, the pore closes.",
    "Stomata close when CO₂ is not needed to prevent excess water loss via transpiration."
  ],
  "keyNotes": [
    "Board Diagram: Practice drawing open stomata (turgid guard cells, curved inner walls) vs closed stomata (flaccid, touching guard cells) with labelled chloroplasts."
  ],
  "questions": [
    get_bank_q(11, "m04_q01"), get_bank_q(12, "m04_q02"), get_bank_q(13, "m04_q03"),
    get_bank_q(14, "m04_q04"), get_bank_q(15, "m04_q05"),
    {
      "id": "m04_q06",
      "question": "What structural feature of guard cell walls allows them to bow outwards and open the stomatal pore when turgid?",
      "options": [
        "The wall is made of pure silica glass.",
        "The outer wall is thin and flexible, while the inner wall facing the pore is thick and inelastic.",
        "The walls contain iron reinforcement bands.",
        "The entire cell wall dissolves in water."
      ],
      "answer": "The outer wall is thin and flexible, while the inner wall facing the pore is thick and inelastic.",
      "explanation": "Differential wall thickness causes the thin outer wall to bulge outward upon water uptake, pulling the thick inner wall apart."
    },
    {
      "id": "m04_q07",
      "question": "What happens to the stomatal pore when guard cells lose water and become flaccid?",
      "options": [
        "The pore opens to maximum diameter.",
        "The pore closes as the inner walls straighten and touch each other.",
        "The stomata fall off the leaf.",
        "The pore turns into a root hair."
      ],
      "answer": "The pore closes as the inner walls straighten and touch each other.",
      "explanation": "Loss of turgor pressure causes guard cells to shrink (become flaccid), closing the stomatal aperture."
    },
    {
      "id": "m04_q08",
      "question": "Why do land plants close their stomata during the hottest afternoon hours or during periods of drought?",
      "options": [
        "To prevent oxygen from entering the leaf.",
        "To conserve water by minimizing transpirational water vapor loss.",
        "To cool the roots down.",
        "To absorb nitrogen gas from the soil."
      ],
      "answer": "To conserve water by minimizing transpirational water vapor loss.",
      "explanation": "Closing stomata halts transpirational water loss, shielding the plant from dehydration and wilting during heat stress."
    },
    {
      "id": "m04_q09",
      "question": "Which ions are actively pumped into guard cells to lower their osmotic potential and trigger the influx of water that opens stomata?",
      "options": [
        "Potassium ions (K⁺)",
        "Iron ions (Fe³⁺)",
        "Lead ions (Pb²⁺)",
        "Aluminium ions (Al³⁺)"
      ],
      "answer": "Potassium ions (K⁺)",
      "explanation": "Active accumulation of K+ ions and malate lowers water potential in guard cells, driving endosmosis and stomatal opening."
    },
    {
      "id": "m04_q10",
      "question": "On which surface of a typical dorsiventral (dicot) leaf are stomata found in the greatest abundance?",
      "options": [
        "Equally on upper and lower surfaces",
        "Predominantly on the lower (abaxial) epidermis",
        "Exclusively on the upper waxy cuticle",
        "Inside the woody stem vessels"
      ],
      "answer": "Predominantly on the lower (abaxial) epidermis",
      "explanation": "Having stomata primarily on the shaded lower surface shields them from direct solar radiation, reducing transpiration."
    }
  ]
}
modules_1_to_10.append(m04)

# Module 5
m05 = {
  "id": "m05", "moduleNumber": 5,
  "title": "Experimental Investigations: Chlorophyll & CO₂ Requirement in Photosynthesis",
  "tagline": "Variegated leaf starch tests and potassium hydroxide (KOH) bell jar investigations.",
  "readingTimeMins": 5,
  "theoryHtml": r"""
<p>To verify the scientific principles of photosynthesis, two classic laboratory investigations are conducted:</p>

<h3>1. Proving Chlorophyll Is Essential (Variegated Leaf Experiment):</h3>
<ul>
  <li><strong>Plant Used:</strong> A potted plant with variegated leaves (leaves having green and non-green white patches, such as <em>Croton</em> or <em>Money plant</em>).</li>
  <li><strong>Destarching Step:</strong> Keep the plant in a pitch-dark room for <strong>$3\text{ days}$</strong> so that all pre-existing starch in the leaves is completely consumed by cellular respiration.</li>
  <li><strong>Light Exposure:</strong> Expose the destarched plant to bright sunlight for about $6\text{ hours}$.</li>
  <li><strong>Starch Testing Procedure:</strong>
    <ol>
      <li>Pluck a leaf and trace the green and white regions on a sheet of tracing paper.</li>
      <li>Boil the leaf in water for a few minutes to soften tissues and break down cell membranes.</li>
      <li>Immerse the leaf in a beaker of <strong>alcohol placed inside a boiling water bath</strong>. (<em>Safety Precaution:</em> Never heat alcohol directly over a burner flame because alcohol is highly flammable!). The alcohol dissolves out green chlorophyll, completely <strong>decolorising the leaf into pale cream</strong>.</li>
      <li>Rinse the leaf in warm water to soften it, then dip it into dilute <strong>iodine solution</strong>.</li>
    </ol>
  </li>
  <li><strong>Observation:</strong> <strong>Only the regions that were originally green turn blue-black</strong>, confirming that starch is formed only where chlorophyll was present.</li>
</ul>

<hr style="border:0; border-top:1px solid #cbd5e1; margin:16px 0;">

<h3>2. Proving Carbon Dioxide Is Essential (KOH Bell Jar Experiment):</h3>
<ul>
  <li>Take two identical healthy destarched potted plants, marked Plant A and Plant B.</li>
  <li>Place both plants on separate flat glass plates under inverted, airtight glass bell jars sealed with <strong>petroleum jelly (Vaseline)</strong>.</li>
  <li>In Bell Jar A, place a watch glass containing <strong>Potassium Hydroxide ($\text{KOH}$) pellets</strong>. Potassium hydroxide chemically <strong>absorbs all carbon dioxide ($\text{CO}_2$)</strong> from the air inside Jar A. Bell Jar B serves as a control with ordinary air.</li>
  <li>Keep both setups in sunlight for $2\text{ hours}$ and perform the iodine starch test on a leaf from each plant.</li>
  <li><strong>Observation:</strong> Leaf from Plant B turns blue-black (starch present), whereas the leaf from Plant A does NOT turn blue-black, proving conclusively that <strong>carbon dioxide is strictly essential for photosynthesis</strong>.</li>
</ul>
""",
  "pointsToRemember": [
    "Destarching (3 days in dark) ensures all pre-existing starch is consumed before starting photosynthesis experiments.",
    "Alcohol decolorises the leaf by dissolving chlorophyll; it must be heated in a water bath because alcohol is flammable.",
    "Iodine turns blue-black in the presence of starch; KOH absorbs CO₂ in bell jar experiments."
  ],
  "keyNotes": [
    "Safety Precaution: Always state why alcohol is heated in a water bath during the starch test—because alcohol is volatile and highly flammable!"
  ],
  "questions": [
    get_bank_q(16, "m05_q01"), get_bank_q(17, "m05_q02"), get_bank_q(18, "m05_q03"),
    get_bank_q(19, "m05_q04"), get_bank_q(20, "m05_q05"),
    {
      "id": "m05_q06",
      "question": "Why is a potted plant placed in a completely dark room for three days prior to conducting photosynthesis experiments?",
      "options": [
        "To destroy all chlorophyll pigments.",
        "To ensure that all previously stored starch in the leaves is completely used up (destarching).",
        "To allow roots to absorb air.",
        "To kill any insects on the leaves."
      ],
      "answer": "To ensure that all previously stored starch in the leaves is completely used up (destarching).",
      "explanation": "Keeping the plant in darkness for 3 days stops photosynthesis so the plant metabolises all existing leaf starch."
    },
    {
      "id": "m05_q07",
      "question": "Why must a green leaf be boiled in alcohol inside a water bath rather than directly over an open burner flame?",
      "options": [
        "Alcohol freezes if exposed to direct flame.",
        "Alcohol is highly inflammable and its vapours can easily catch fire if heated directly over a burner.",
        "The water bath makes the leaf turn purple.",
        "Direct flame destroys the iodine solution."
      ],
      "answer": "Alcohol is highly inflammable and its vapours can easily catch fire if heated directly over a burner.",
      "explanation": "Alcohol has a low flash point and is dangerously flammable; a water bath provides safe, indirect heating."
    },
    {
      "id": "m05_q08",
      "question": "What is the specific chemical function of potassium hydroxide (KOH) placed inside Bell Jar A in the photosynthesis investigation?",
      "options": [
        "To produce oxygen gas inside the jar",
        "To absorb all carbon dioxide (CO₂) from the enclosed atmosphere",
        "To provide moisture for the plant roots",
        "To act as an artificial light source"
      ],
      "answer": "To absorb all carbon dioxide (CO₂) from the enclosed atmosphere",
      "explanation": "KOH reacts chemically with CO₂ (2KOH + CO₂ -> K₂CO₃ + H₂O), creating a CO₂-free environment."
    },
    {
      "id": "m05_q09",
      "question": "What reagent is applied to a decolorised leaf to test for the presence of synthesized starch, and what color change signifies a positive result?",
      "options": [
        "Benedict's reagent, turning red",
        "Dilute iodine solution, turning blue-black",
        "Methylene blue, turning clear",
        "Litmus solution, turning green"
      ],
      "answer": "Dilute iodine solution, turning blue-black",
      "explanation": "Iodine forms a deep blue-black polyiodide complex with the helical amylose chains of starch."
    },
    {
      "id": "m05_q10",
      "question": "Why is Vaseline (petroleum jelly) applied to the bottom rim of the glass bell jar and glass plate in photosynthesis setups?",
      "options": [
        "To attract ants to the experiment",
        "To create an airtight seal preventing atmospheric air from leaking into the apparatus",
        "To lubricate the glass so it rotates",
        "To filter sunlight wavelengths"
      ],
      "answer": "To create an airtight seal preventing atmospheric air from leaking into the apparatus",
      "explanation": "Vaseline forms an airtight boundary, preventing external CO₂ from seeping into the experimental chamber."
    }
  ]
}
modules_1_to_10.append(m05)

# Module 6
m06 = {
  "id": "m06", "moduleNumber": 6,
  "title": "Heterotrophic Nutrition: Saprophytic, Parasitic & Holozoic (Amoeba & Paramoecium)",
  "tagline": "External digestion, parasitic exploitation, and phagocytosis in single-celled protozoans.",
  "readingTimeMins": 5,
  "theoryHtml": r"""
<p>Each organism is adapted to its environment. Heterotrophs cannot manufacture their own food from inorganic materials; they depend directly or indirectly on autotrophs. Heterotrophic nutrition is broadly categorized into three distinct strategies:</p>

<h3>1. Modes of Heterotrophic Nutrition:</h3>
<ul>
  <li><strong>Saprophytic Nutrition:</strong> Organisms break down food materials <em>outside the body</em> by secreting digestive enzymes onto dead and decaying matter, then absorb the liquefied nutrients. Examples: Fungi (bread mould <em>Rhizopus</em>, yeast, mushrooms).</li>
  <li><strong>Parasitic Nutrition:</strong> Organisms derive nutrients directly from the body of another living host organism without killing it. Examples: Plants like <em>Cuscuta</em> (Amarbel), orchids; Animals like ticks, lice, tapeworms, and leeches.</li>
  <li><strong>Holozoic Nutrition:</strong> Organisms ingest complex solid or liquid organic food into their bodies, where it is digested internally into simpler absorbable molecules. Examples: Humans, dogs, Amoeba, Paramoecium.</li>
</ul>

<hr style="border:0; border-top:1px solid #cbd5e1; margin:16px 0;">

<h3>2. Nutrition in Single-Celled Organisms:</h3>
<ul>
  <li><strong>Amoeba:</strong>
    <ul>
      <li>Captures food using temporary finger-like cellular extensions called <strong>pseudopodia</strong> ('false feet').</li>
      <li>Pseudopodia fuse over the food particle, engulfing it to form an internal membrane-bound <strong>food vacuole</strong>.</li>
      <li>Inside the food vacuole, complex food substances are broken down into simpler molecules by digestive enzymes, which diffuse directly into the cytoplasm.</li>
      <li>The remaining undigested material is moved to the surface of the cell and ejected out by exocytosis.</li>
    </ul>
  </li>
  <li><strong>Paramoecium:</strong>
    <ul>
      <li>Has a fixed, definite slipper-shaped body.</li>
      <li>Food is taken in at a specific, designated intake spot (the <strong>oral groove / cytostome</strong>).</li>
      <li>Food is swept toward this spot by the rhythmic, coordinated beating of thousands of microscopic, hair-like <strong>cilia</strong> covering the entire cell surface.</li>
    </ul>
  </li>
</ul>
""",
  "pointsToRemember": [
    "Saprophytes (fungi, mushrooms) digest food externally and absorb nutrients.",
    "Parasites (Cuscuta, ticks, tapeworms) derive nutrition from living hosts without killing them.",
    "Amoeba engulfs food using pseudopodia to form a food vacuole; Paramoecium uses cilia to move food to an oral groove."
  ],
  "keyNotes": [
    "Exam Question: Contrast nutrition in Amoeba (pseudopodia engulf food anywhere into a food vacuole) with Paramoecium (cilia sweep food to a specific fixed oral groove)."
  ],
  "questions": [
    get_bank_q(21, "m06_q01"), get_bank_q(22, "m06_q02"), get_bank_q(23, "m06_q03"),
    get_bank_q(24, "m06_q04"), get_bank_q(25, "m06_q05"),
    {
      "id": "m06_q06",
      "question": "Which of the following organisms breaks down food materials outside its body into a liquid form before absorbing it (saprophytic mode)?",
      "options": [
        "Amoeba",
        "Bread mould (Rhizopus) and mushrooms",
        "Cuscuta (Amarbel)",
        "Paramoecium"
      ],
      "answer": "Bread mould (Rhizopus) and mushrooms",
      "explanation": "Saprophytic fungi release extracellular enzymes onto decaying organic matter and absorb pre-digested nutrients."
    },
    {
      "id": "m06_q07",
      "question": "Which plant is a classic example of a parasitic organism that derives ready-made nutrients from host trees without possessing chlorophyll?",
      "options": [
        "Croton",
        "Cuscuta (Amarbel)",
        "Money plant",
        "Bryophyllum"
      ],
      "answer": "Cuscuta (Amarbel)",
      "explanation": "Cuscuta is a non-green parasitic plant that sends haustorial roots into host vascular tissues to drain food."
    },
    {
      "id": "m06_q08",
      "question": "What temporary cellular extensions does an Amoeba extend to engulf food particles into a food vacuole?",
      "options": [
        "Cilia",
        "Pseudopodia ('false feet')",
        "Flagella",
        "Tentacles"
      ],
      "answer": "Pseudopodia ('false feet')",
      "explanation": "Amoeba uses flowing cytoplasm extensions called pseudopodia to surround food and form a food vacuole."
    },
    {
      "id": "m06_q09",
      "question": "How does Paramoecium propel food particles into its specific intake spot (oral groove)?",
      "options": [
        "By extending large pseudopodia",
        "Through the coordinated rhythmic beating of hair-like cilia covering its cell surface",
        "By secreting acidic bile juice",
        "By using teeth"
      ],
      "answer": "Through the coordinated rhythmic beating of hair-like cilia covering its cell surface",
      "explanation": "Paramoecium has a fixed cytostome; cilia beating in wave-like coordination drive water currents carrying food into the groove."
    },
    {
      "id": "m06_q10",
      "question": "What happens to the unabsorbed, undigested residual waste in an Amoeba after digestion is complete?",
      "options": [
        "It turns into poisonous urea inside the cell.",
        "It is transported to the cell membrane surface and ejected to the outside.",
        "It is permanently stored as bone.",
        "It evaporates through the nucleus."
      ],
      "answer": "It is transported to the cell membrane surface and ejected to the outside.",
      "explanation": "Undigested residue fuses with the plasma membrane and is expelled into surrounding water by exocytosis."
    }
  ]
}
modules_1_to_10.append(m06)

# Module 7
m07 = {
  "id": "m07", "moduleNumber": 7,
  "title": "Human Alimentary Canal: Ingestion, Salivary Amylase & Peristalsis",
  "tagline": "Mechanical mastication, chemical starch breakdown, and esophageal transport.",
  "readingTimeMins": 5,
  "theoryHtml": r"""
<p>The human digestive system consists of a continuous muscular tube extending from the mouth to the anus, known as the <strong>alimentary canal</strong> (approximately $9\text{ metres}$ long in an adult), along with associated digestive glands.</p>

<h3>1. Ingestion and the Buccal Cavity (Mouth):</h3>
<ul>
  <li>Food is taken into the mouth, where it is mechanically crushed and masticated by our <strong>teeth</strong> into smaller pieces.</li>
  <li>The muscular <strong>tongue</strong> mixes the chewed food thoroughly with <strong>saliva</strong> secreted by three pairs of <strong>salivary glands</strong>.</li>
</ul>

<h3>2. Chemical Digestion in the Mouth — Salivary Amylase:</h3>
<p>Saliva contains a watery fluid that wets and lubricates food for smooth swallowing, plus a vital digestive enzyme called <strong>salivary amylase</strong> (historically called ptyalin):</p>
<p style="text-align:center; font-weight:bold; color:#1e3a8a;">
  $\text{Starch (Complex Carbohydrate)} \xrightarrow[\text{pH } \approx 6.8]{\text{Salivary Amylase}} \text{Maltose (Simpler Sugar)}$
</p>
<p>Salivary amylase hydrolyses approximately $30\%$ of dietary starch into the disaccharide maltose right inside the oral cavity!</p>

<h3>3. Transport Through the Oesophagus — Peristalsis:</h3>
<ul>
  <li>The moistened, chewed food bolus passes into the food pipe (<strong>oesophagus</strong>).</li>
  <li>The lining of the alimentary canal has muscles that contract and relax rhythmically in order to push food forward in a regulated manner.</li>
  <li>These involuntary, wave-like muscular contractions of the canal wall are termed <strong>peristaltic movements (peristalsis)</strong>. Peristalsis occurs throughout the entire length of the gut from oesophagus to rectum.</li>
</ul>
""",
  "pointsToRemember": [
    "Salivary amylase in saliva breaks down complex starch into simpler sugars (maltose) in the mouth.",
    "The tongue mixes food with saliva, forming a lubricated bolus for easy swallowing.",
    "Peristalsis is the rhythmic, wave-like contraction of muscular walls pushing food along the alimentary canal."
  ],
  "keyNotes": [
    "Exam Question: What enzyme is present in human saliva, what substrate does it digest, and what is the product? (Salivary amylase breaks starch into maltose)."
  ],
  "questions": [
    get_bank_q(26, "m07_q01"), get_bank_q(27, "m07_q02"), get_bank_q(28, "m07_q03"),
    get_bank_q(29, "m07_q04"), get_bank_q(30, "m07_q05"),
    {
      "id": "m07_q06",
      "question": "What specific biochemical reaction is catalyzed by salivary amylase enzyme present in human saliva?",
      "options": [
        "Conversion of proteins into amino acids",
        "Hydrolysis of complex starch into simpler sugars (maltose)",
        "Emulsification of dietary fats into fatty acids",
        "Neutralisation of gastric acid"
      ],
      "answer": "Hydrolysis of complex starch into simpler sugars (maltose)",
      "explanation": "Salivary amylase breaks alpha-1,4-glycosidic bonds in starch, converting it into maltose and dextrins."
    },
    {
      "id": "m07_q07",
      "question": "What term describes the rhythmic, involuntary wave-like muscular contractions of the alimentary canal that push food downward?",
      "options": [
        "Translocation",
        "Peristaltic movements (Peristalsis)",
        "Dialysis",
        "Phagocytosis"
      ],
      "answer": "Peristaltic movements (Peristalsis)",
      "explanation": "Peristalsis consists of coordinated alternating muscular contraction and relaxation that moves food along the gut."
    },
    {
      "id": "m07_q08",
      "question": "If salivary amylase is deficient or missing from a person's saliva, which of the following events in the buccal cavity will be directly impaired?",
      "options": [
        "Proteins breaking down into amino acids",
        "Starch breaking down into sugars",
        "Fats breaking down into glycerol",
        "Absorption of vitamins"
      ],
      "answer": "Starch breaking down into sugars",
      "explanation": "Without salivary amylase, initial enzymatic starch breakdown into maltose in the mouth cannot occur."
    },
    {
      "id": "m07_q09",
      "question": "Does any significant chemical digestion of food take place inside the oesophagus (food pipe)?",
      "options": [
        "Yes, protein digestion begins in the oesophagus.",
        "No, the oesophagus secretes only lubricating mucus and serves solely to transport the bolus to the stomach via peristalsis.",
        "Yes, all fats are completely absorbed in the oesophagus.",
        "Yes, hydrochloric acid is secreted by oesophageal walls."
      ],
      "answer": "No, the oesophagus secretes only lubricating mucus and serves solely to transport the bolus to the stomach via peristalsis.",
      "explanation": "The oesophagus contains no digestive glands; its muscular wall merely conveys the bolus via peristalsis."
    },
    {
      "id": "m07_q10",
      "question": "Why does a piece of plain bread or boiled rice begin to taste slightly sweet after being chewed in the mouth for a couple of minutes?",
      "options": [
        "Saliva contains table sugar.",
        "Salivary amylase enzymatically converts tasteless complex starch into sweet-tasting maltose sugar.",
        "Teeth release glucose when chewing.",
        "The tongue produces artificial sweeteners."
      ],
      "answer": "Salivary amylase enzymatically converts tasteless complex starch into sweet-tasting maltose sugar.",
      "explanation": "Prolonged mastication allows salivary amylase to break starch into sweet-tasting maltose disaccharides."
    }
  ]
}
modules_1_to_10.append(m07)

# Module 8
m08 = {
  "id": "m08", "moduleNumber": 8,
  "title": "Digestion in the Stomach: Gastric Glands (HCl, Pepsin, Mucus) & Sphincters",
  "tagline": "Acidic microenvironment, proteolytic digestion, mucosal protection, and chyme.",
  "readingTimeMins": 5,
  "theoryHtml": r"""
<p>From the oesophagus, food enters the <strong>stomach</strong>, a large J-shaped muscular organ that expands when food enters it. The muscular walls of the stomach churn and mix the food thoroughly with digestive juices secreted by the <strong>gastric glands</strong> located in the stomach wall.</p>

<h3>The Three Vital Secretions of Gastric Glands:</h3>
<ol>
  <li><strong>Hydrochloric Acid ($\text{HCl}$):</strong>
    <ul>
      <li>Creates an intensely <strong>acidic medium</strong> ($\text{pH} \approx 1.5 - 2.0$) necessary for the activation and optimal functioning of the enzyme pepsin.</li>
      <li>Kills harmful bacteria and pathogens ingested along with food.</li>
      <li>Softens tough fibrous food materials.</li>
    </ul>
  </li>
  <li><strong>Pepsin (Pepsinogen):</strong>
    <ul>
      <li>Secreted in an inactive precursor form (pepsinogen) to prevent self-digestion of gastric tissues.</li>
      <li>$\text{HCl}$ activates inactive pepsinogen into active <strong>pepsin</strong>.</li>
      <li>Pepsin is a proteolytic enzyme that breaks down complex dietary <strong>proteins into smaller peptides (peptones and proteoses)</strong>.</li>
    </ul>
  </li>
  <li><strong>Mucus:</strong>
    <ul>
      <li>Forms a continuous, thick, slippery physical barrier over the inner stomach lining.</li>
      <li><strong>Protects the delicate stomach wall</strong> from the corrosive, burning action of concentrated hydrochloric acid and self-digestion by pepsin.</li>
      <li><em>Clinical Connection:</em> If mucus secretion is compromised (due to stress, aspirin abuse, or <em>H. pylori</em> infection), excess acid erodes the stomach wall, producing painful <strong>gastric ulcers</strong> and acute acidity.</li>
    </ul>
  </li>
</ol>

<h3>Exit of Food from the Stomach:</h3>
<p>The semi-solid, acidic, pulpy food mass produced in the stomach is called <strong>chyme</strong>. Its exit into the small intestine is strictly regulated by a circular muscular valve called the <strong>pyloric sphincter</strong>, which releases chyme in small, controlled spurts.</p>
""",
  "pointsToRemember": [
    "Gastric glands secrete Hydrochloric acid (HCl), Pepsin, and Mucus.",
    "HCl creates an acidic medium (pH ~1.5-2) essential for pepsin to digest proteins, and kills ingested bacteria.",
    "Mucus protects the inner stomach lining from being eroded by hydrochloric acid; pyloric sphincter regulates chyme exit."
  ],
  "keyNotes": [
    "Common Board Question: What would happen if the gastric glands did not secrete mucus? The inner lining of the stomach would be eroded by concentrated HCl, leading to severe acidity and gastric ulcers."
  ],
  "questions": [
    get_bank_q(66, "m08_q01"), get_bank_q(67, "m08_q02"), get_bank_q(68, "m08_q03"),
    get_bank_q(69, "m08_q04"), get_bank_q(70, "m08_q05"),
    {
      "id": "m08_q06",
      "question": "What is the primary biological danger if the gastric glands fail to produce an adequate layer of mucus inside the stomach?",
      "options": [
        "Protein digestion will occur too rapidly.",
        "The concentrated hydrochloric acid will erode and corrode the inner stomach lining, causing painful gastric ulcers.",
        "The stomach will turn into an alkaline organ.",
        "Food will freeze inside the stomach."
      ],
      "answer": "The concentrated hydrochloric acid will erode and corrode the inner stomach lining, causing painful gastric ulcers.",
      "explanation": "Mucus coats the gastric epithelium; without it, acidic gastric juice digests the stomach wall, resulting in ulceration."
    },
    {
      "id": "m08_q07",
      "question": "Why is the presence of hydrochloric acid (HCl) strictly required for protein digestion inside the human stomach?",
      "options": [
        "HCl converts starch into glucose.",
        "HCl activates the inactive enzyme precursor pepsinogen into active proteolytic pepsin and maintains the optimal low pH (~1.5-2.0).",
        "HCl digests all dietary lipids.",
        "HCl causes teeth to grow."
      ],
      "answer": "HCl activates the inactive enzyme precursor pepsinogen into active proteolytic pepsin and maintains the optimal low pH (~1.5-2.0).",
      "explanation": "Pepsin operates strictly in a highly acidic pH; HCl cleaves pepsinogen into active pepsin to hydrolyse proteins."
    },
    {
      "id": "m08_q08",
      "question": "What muscular ring regulates the release of acidic chyme from the stomach into the duodenum of the small intestine?",
      "options": [
        "Anal sphincter",
        "Pyloric sphincter",
        "Cardiac sphincter",
        "Ileocaecal valve"
      ],
      "answer": "Pyloric sphincter",
      "explanation": "The pyloric sphincter controls the rate at which acidic chyme passes from the pylorus of the stomach into the duodenum."
    },
    {
      "id": "m08_q09",
      "question": "What class of macronutrients does the gastric enzyme pepsin specifically begin breaking down?",
      "options": [
        "Carbohydrates",
        "Fats and oils",
        "Proteins (breaking them into peptones and proteoses)",
        "Dietary cellulose"
      ],
      "answer": "Proteins (breaking them into peptones and proteoses)",
      "explanation": "Pepsin is an endopeptidase that cleaves peptide bonds in complex proteins, yielding shorter peptides."
    },
    {
      "id": "m08_q10",
      "question": "What is the acidic, pulpy, semi-fluid mass of partially digested food that leaves the stomach called?",
      "options": [
        "Bolus",
        "Chyme",
        "Chyle",
        "Faeces"
      ],
      "answer": "Chyme",
      "explanation": "Partially digested, acidic fluid food exiting the stomach through the pyloric valve is termed chyme."
    }
  ]
}
modules_1_to_10.append(m08)

# Module 9
m09 = {
  "id": "m09", "moduleNumber": 9,
  "title": "The Small Intestine: Bile Emulsification & Pancreatic Enzymes",
  "tagline": "Alkaline conversion, lipid emulsification, trypsin, lipase, and complete digestion.",
  "readingTimeMins": 5,
  "theoryHtml": r"""
<p>The <strong>small intestine</strong> is the longest part of the alimentary canal (around $6.5\text{ metres}$ long in adults, fitted compactly by extensive coiling). It is the <strong>site of complete digestion</strong> of carbohydrates, proteins, and fats.</p>

<h3>Comparative Length of Small Intestine:</h3>
<ul>
  <li><strong>Herbivores (e.g. cows):</strong> Have a <strong>longer small intestine</strong> because digesting fibrous cellulose requires more time and specialised bacterial fermentation.</li>
  <li><strong>Carnivores (e.g. tigers):</strong> Have a <strong>shorter small intestine</strong> because meat is much easier to digest.</li>
</ul>

<h3>Coordinated Secretions Entering the Small Intestine:</h3>
<p>The small intestine receives digestive secretions from two major accessory organs:</p>

<h3>1. Bile from the Liver (Stored in Gall Bladder):</h3>
<ul>
  <li><strong>Alkaline Conversion:</strong> The food arriving from the stomach is acidic. Bile juice contains sodium bicarbonate and bile salts that neutralize gastric acid and turn the chyme <strong>alkaline</strong> ($\text{pH} \approx 7.8 - 8.2$), which is mandatory for pancreatic enzymes to act.</li>
  <li><strong>Emulsification of Fats:</strong> Dietary fats enter the intestine as large, insolubilised globules, making it difficult for water-soluble enzymes to act. <strong>Bile salts break down large fat globules into tiny droplets</strong> (similar to the action of soap on oily dirt). This physical process is called <strong>emulsification</strong>, and it tremendously increases the surface area for enzyme action.</li>
</ul>

<h3>2. Pancreatic Juice from the Pancreas:</h3>
<ul>
  <li><strong>Trypsin:</strong> Digests proteins and peptides into smaller peptides and amino acids in the alkaline medium.</li>
  <li><strong>Pancreatic Amylase:</strong> Continues the breakdown of remaining starch into maltose.</li>
  <li><strong>Lipase:</strong> Digests emulsified fat droplets into <strong>fatty acids and glycerol</strong>.</li>
</ul>

<h3>3. Intestinal Juice (Succus Entericus):</h3>
<p>Glands in the intestinal walls secrete intestinal juice containing final enzymes that complete the digestion of all food constituents:</p>
<ul>
  <li>Complex Carbohydrates $\longrightarrow$ <strong>Glucose</strong></li>
  <li>Proteins $\longrightarrow$ <strong>Amino Acids</strong></li>
  <li>Fats $\longrightarrow$ <strong>Fatty Acids and Glycerol</strong></li>
</ul>
""",
  "pointsToRemember": [
    "Herbivores have a longer small intestine to digest cellulose; carnivores have a shorter intestine.",
    "Bile from the liver neutralizes acidic chyme (making it alkaline) and emulsifies large fat globules into tiny droplets.",
    "Pancreatic juice contains Trypsin (digests proteins), Lipase (digests emulsified fats), and Amylase.",
    "Final digestion products: Carbohydrates → Glucose; Proteins → Amino Acids; Fats → Fatty acids + Glycerol."
  ],
  "keyNotes": [
    "Core Concept: Bile juice contains NO digestive enzymes, yet is indispensable for digestion! State why: 1) Makes medium alkaline, 2) Emulsifies fats."
  ],
  "questions": [
    get_bank_q(71, "m09_q01"), get_bank_q(72, "m09_q02"), get_bank_q(73, "m09_q03"),
    get_bank_q(74, "m09_q04"), get_bank_q(75, "m09_q05"),
    {
      "id": "m09_q06",
      "question": "Why do herbivorous mammals (such as cows and deer) possess a significantly longer small intestine than carnivores (such as tigers)?",
      "options": [
        "Herbivores eat large rocks that require space.",
        "Digesting tough, fibrous plant cellulose requires extended transit time and microbial fermentation in a longer intestine.",
        "Herbivores run faster, stretching their intestines.",
        "Carnivores have no small intestine."
      ],
      "answer": "Digesting tough, fibrous plant cellulose requires extended transit time and microbial fermentation in a longer intestine.",
      "explanation": "Cellulose is difficult to hydrolyse, requiring prolonged contact with symbiotic gut flora in an elongated intestine."
    },
    {
      "id": "m09_q07",
      "question": "Although bile juice contains ZERO digestive enzymes, why is it considered completely essential for human digestion?",
      "options": [
        "Bile juice provides calories for the liver.",
        "Bile makes the acidic chyme alkaline (enabling pancreatic enzymes to work) and emulsifies large fat globules into tiny droplets.",
        "Bile turns all proteins into vitamins.",
        "Bile digests starch into glucose."
      ],
      "answer": "Bile makes the acidic chyme alkaline (enabling pancreatic enzymes to work) and emulsifies large fat globules into tiny droplets.",
      "explanation": "Bile salts neutralise stomach acid and physically disperse fats (emulsification), vastly expanding surface area for lipase."
    },
    {
      "id": "m09_q08",
      "question": "What are the three final end products of complete digestion for carbohydrates, proteins, and fats respectively in the small intestine?",
      "options": [
        "Starch, peptones, and soap",
        "Glucose, Amino acids, and Fatty acids + Glycerol",
        "Glycogen, urea, and carbon dioxide",
        "Sucrose, ammonia, and cholesterol"
      ],
      "answer": "Glucose, Amino acids, and Fatty acids + Glycerol",
      "explanation": "Complete digestion reduces carbs to glucose, proteins to amino acids, and fats to fatty acids and glycerol."
    },
    {
      "id": "m09_q09",
      "question": "Which pancreatic enzyme is responsible for the digestion of emulsified dietary fats into fatty acids and glycerol?",
      "options": [
        "Trypsin",
        "Pancreatic Lipase",
        "Pepsin",
        "Salivary Amylase"
      ],
      "answer": "Pancreatic Lipase",
      "explanation": "Lipase specifically hydrolyses ester bonds in emulsified triglyceride fat droplets into fatty acids and glycerol."
    },
    {
      "id": "m09_q10",
      "question": "A patient undergoes cholecystectomy (surgical removal of the gall bladder due to gallstones). Which dietary component must they temporarily restrict?",
      "options": [
        "Refined carbohydrates",
        "Oily, high-fat meals (since bile cannot be stored and concentrated for rapid fat emulsification)",
        "Dietary fiber",
        "Table salt"
      ],
      "answer": "Oily, high-fat meals (since bile cannot be stored and concentrated for rapid fat emulsification)",
      "explanation": "Without a gall bladder to store bile, continuous dilute bile output struggles to emulsify sudden heavy dietary fat loads."
    }
  ]
}
modules_1_to_10.append(m09)

# Module 10
m10 = {
  "id": "m10", "moduleNumber": 10,
  "title": "Absorption via Villi, Large Intestine & Dental Caries",
  "tagline": "Microscopic villi, water reabsorption, egestion, and bacterial dental plaque.",
  "readingTimeMins": 5,
  "theoryHtml": r"""
<h3>1. Absorption in the Small Intestine — The Villi:</h3>
<p>The digested food nutrients are absorbed through the inner wall of the small intestine:</p>
<ul>
  <li>The inner mucosal lining of the small intestine features millions of tiny, finger-like projections called <strong>villi</strong> (singular: villus).</li>
  <li><strong>Surface Area Amplification:</strong> Villi increase the internal surface area of absorption exponentially (roughly the surface area of a tennis court!).</li>
  <li><strong>Rich Vascular Supply:</strong> Each villus is richly supplied with a dense network of blood capillaries and a central lymph vessel called a <strong>lacteal</strong>.</li>
  <li>Glucose, amino acids, minerals, and water-soluble vitamins are absorbed directly into the <strong>bloodstream</strong> and transported to all body cells for energy release and tissue repair (<strong>assimilation</strong>).</li>
  <li>Fatty acids and glycerol are absorbed into the <strong>lacteals (lymph)</strong> before entering general circulation.</li>
</ul>

<h3>2. The Large Intestine and Egestion:</h3>
<ul>
  <li>The unabsorbed, undigested food material passes into the <strong>large intestine</strong> (colon).</li>
  <li>The wall of the large intestine possesses villi that <strong>reabsorb excess water</strong> and mineral salts from the unabsorbed material.</li>
  <li>The remaining semi-solid waste matter (faeces) is stored in the <strong>rectum</strong> and eliminated from the body through the anus (<strong>egestion</strong>), strictly regulated by the <strong>anal sphincter</strong>.</li>
</ul>

<hr style="border:0; border-top:1px solid #cbd5e1; margin:16px 0;">

<h3>3. Dental Caries (Tooth Decay):</h3>
<ul>
  <li><strong>Mechanism:</strong> Tooth enamel (hardest substance in the body, made of calcium hydroxyapatite) is attacked by acids. When sugar-rich foods are eaten, oral bacteria ferment the sugars, generating organic acids.</li>
  <li><strong>Dental Plaque:</strong> Bacterial colonies combine with saliva and food debris to form a sticky, yellowish film called <strong>dental plaque</strong> that coats the teeth. Plaque blocks saliva from reaching the tooth surface to neutralise bacterial acids.</li>
  <li><strong>Prevention:</strong> Brushing teeth after meals mechanically removes plaque before bacteria produce acids. Most toothpastes are <strong>mildly alkaline</strong>, which neutralises residual acids and prevents enamel demineralisation.</li>
</ul>
""",
  "pointsToRemember": [
    "Villi are finger-like projections in the small intestine that vastly expand surface area for nutrient absorption.",
    "Villi have blood capillaries (absorb glucose and amino acids) and lacteals (absorb fatty acids and glycerol).",
    "The large intestine reabsorbs water from waste; dental plaque is a bacterial film that causes enamel demineralisation."
  ],
  "keyNotes": [
    "Board Highlight: Describe the adaptations of the small intestine for absorption: 1) Great length, 2) Millions of villi, 3) Thin epithelial walls, 4) Rich capillary and lacteal blood supply."
  ],
  "questions": [
    get_bank_q(56, "m10_q01"), get_bank_q(57, "m10_q02"), get_bank_q(58, "m10_q03"),
    get_bank_q(59, "m10_q04"), get_bank_q(60, "m10_q05"),
    {
      "id": "m10_q06",
      "question": "What anatomical adaptations enable the human small intestine to absorb digested food with such high efficiency?",
      "options": [
        "It contains hard bones that squeeze food.",
        "It has an enormous length, millions of finger-like villi expanding surface area, and a rich network of blood capillaries and lacteals.",
        "It is filled with dry air.",
        "It has thick leather walls that block water."
      ],
      "answer": "It has an enormous length, millions of finger-like villi expanding surface area, and a rich network of blood capillaries and lacteals.",
      "explanation": "The extensive surface area of villi, thin epithelium, and dense capillary networks maximize absorption rate."
    },
    {
      "id": "m10_q07",
      "question": "Into which specialized microscopic vessels inside the intestinal villi are absorbed fatty acids and glycerol initially taken up?",
      "options": [
        "Renal arteries",
        "Lacteals (lymphatic vessels)",
        "Pulmonary veins",
        "Bile ducts"
      ],
      "answer": "Lacteals (lymphatic vessels)",
      "explanation": "Fats are repackaged into chylomicrons and absorbed into central lacteals of the lymphatic system."
    },
    {
      "id": "m10_q08",
      "question": "What is the primary physiological function of the human large intestine (colon)?",
      "options": [
        "Digesting dietary proteins into amino acids",
        "Reabsorbing excess water and mineral salts from unabsorbed waste material",
        "Secreting hydrochloric acid",
        "Filtering urea from blood"
      ],
      "answer": "Reabsorbing excess water and mineral salts from unabsorbed waste material",
      "explanation": "The colon absorbs water and electrolytes from indigestible chyme, consolidating it into semi-solid faeces."
    },
    {
      "id": "m10_q09",
      "question": "How does dental plaque contribute to the formation of tooth cavities (dental caries)?",
      "options": [
        "Plaque is an acid that burns teeth instantly.",
        "Plaque forms a sticky bacterial film over teeth that prevents alkaline saliva from neutralizing acid produced by bacteria fermenting sugars.",
        "Plaque removes all calcium from the blood.",
        "Plaque causes teeth to turn into bone."
      ],
      "answer": "Plaque forms a sticky bacterial film over teeth that prevents alkaline saliva from neutralizing acid produced by bacteria fermenting sugars.",
      "explanation": "The barrier created by plaque prevents saliva from contacting the tooth enamel to neutralise bacterial acids."
    },
    {
      "id": "m10_q10",
      "question": "Why are commercial toothpastes formulated to be mildly alkaline (basic) in nature?",
      "options": [
        "To stain the teeth white",
        "To neutralise excess organic acids produced by mouth bacteria, preventing enamel demineralisation",
        "To dissolve the teeth",
        "To digest dietary proteins"
      ],
      "answer": "To neutralise excess organic acids produced by mouth bacteria, preventing enamel demineralisation",
      "explanation": "Mildly basic toothpaste neutralises bacterial acid in the mouth, safeguarding calcium hydroxyapatite enamel."
    }
  ]
}
modules_1_to_10.append(m10)

with open('scratch/ch5_part1.json', 'w', encoding='utf-8') as f:
    json.dump(modules_1_to_10, f, ensure_ascii=False, indent=2)

print(f"Successfully generated Chapter 5 Part 1 (Modules 1 to 10): {len(modules_1_to_10)} modules.")
